version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: facebookApp
    ports:
      - 9000:9000
    volumes:
      - ./:/home/app

  db:
    image: mysql:5.7
    container_name: facebookDB
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_USER: 'test'
    ports:
      - 3306:3306
    volumes:
      - ./dbData:/var/lib/mysql